In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("car data.csv")
df

Car_Name  Year  Selling_Price  Present_Price  Driven_kms Fuel_Type  \
0       ritz  2014           3.35           5.59       27000    Petrol   
1        sx4  2013           4.75           9.54       43000    Diesel   
2       ciaz  2017           7.25           9.85        6900    Petrol   
3    wagon r  2011           2.85           4.15        5200    Petrol   
4      swift  2014           4.60           6.87       42450    Diesel   
..       ...   ...            ...            ...         ...       ...   
296     city  2016           9.50          11.60       33988    Diesel   
297     brio  2015           4.00           5.90       60000    Petrol   
298     city  2009           3.35          11.00       87934    Petrol   
299     city  2017          11.50          12.50        9000    Diesel   
300     brio  2016           5.30           5.90        5464    Petrol   

    Selling_type Transmission  Owner  
0         Dealer       Manual      0  
1         Dealer       Manual      0  
2         Dealer       Manual      0  
3         Dealer       Manual      0  
4         Dealer       Manual      0  
..           ...          ...    ...  
296       Dealer       Manual      0  
297       Dealer       Manual      0  
298       Dealer       Manual      0  
299       Dealer       Manual      0  
300       Dealer       Manual      0  

[301 rows x 9 columns]

In [3]:
df.head()

Car_Name  Year  Selling_Price  Present_Price  Driven_kms Fuel_Type  \
0     ritz  2014           3.35           5.59       27000    Petrol   
1      sx4  2013           4.75           9.54       43000    Diesel   
2     ciaz  2017           7.25           9.85        6900    Petrol   
3  wagon r  2011           2.85           4.15        5200    Petrol   
4    swift  2014           4.60           6.87       42450    Diesel   

  Selling_type Transmission  Owner  
0       Dealer       Manual      0  
1       Dealer       Manual      0  
2       Dealer       Manual      0  
3       Dealer       Manual      0  
4       Dealer       Manual      0

In [4]:
df.tail()

Car_Name  Year  Selling_Price  Present_Price  Driven_kms Fuel_Type  \
296     city  2016           9.50           11.6       33988    Diesel   
297     brio  2015           4.00            5.9       60000    Petrol   
298     city  2009           3.35           11.0       87934    Petrol   
299     city  2017          11.50           12.5        9000    Diesel   
300     brio  2016           5.30            5.9        5464    Petrol   

    Selling_type Transmission  Owner  
296       Dealer       Manual      0  
297       Dealer       Manual      0  
298       Dealer       Manual      0  
299       Dealer       Manual      0  
300       Dealer       Manual      0

In [5]:
df.describe()

Year  Selling_Price  Present_Price     Driven_kms       Owner
count   301.000000     301.000000     301.000000     301.000000  301.000000
mean   2013.627907       4.661296       7.628472   36947.205980    0.043189
std       2.891554       5.082812       8.642584   38886.883882    0.247915
min    2003.000000       0.100000       0.320000     500.000000    0.000000
25%    2012.000000       0.900000       1.200000   15000.000000    0.000000
50%    2014.000000       3.600000       6.400000   32000.000000    0.000000
75%    2016.000000       6.000000       9.900000   48767.000000    0.000000
max    2018.000000      35.000000      92.600000  500000.000000    3.000000

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 301 entries, 0 to 300
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Car_Name       301 non-null    object 
 1   Year           301 non-null    int64  
 2   Selling_Price  301 non-null    float64
 3   Present_Price  301 non-null    float64
 4   Driven_kms     301 non-null    int64  
 5   Fuel_Type      301 non-null    object 
 6   Selling_type   301 non-null    object 
 7   Transmission   301 non-null    object 
 8   Owner          301 non-null    int64  
dtypes: float64(2), int64(3), object(4)
memory usage: 21.3+ KB


In [7]:
df.isnull().sum()

Car_Name         0
Year             0
Selling_Price    0
Present_Price    0
Driven_kms       0
Fuel_Type        0
Selling_type     0
Transmission     0
Owner            0
dtype: int64

In [8]:
from sklearn.preprocessing import LabelEncoder

In [10]:
#Label encoding
label=LabelEncoder()
df['Car_Name']=label.fit_transform(df['Car_Name'])
df['Fuel_Type']=label.fit_transform(df['Fuel_Type'])
df['Selling_type']=label.fit_transform(df['Selling_type'])
df['Transmission']=label.fit_transform(df['Transmission'])

In [11]:
df

Car_Name  Year  Selling_Price  Present_Price  Driven_kms  Fuel_Type  \
0          90  2014           3.35           5.59       27000          2   
1          93  2013           4.75           9.54       43000          1   
2          68  2017           7.25           9.85        6900          2   
3          96  2011           2.85           4.15        5200          2   
4          92  2014           4.60           6.87       42450          1   
..        ...   ...            ...            ...         ...        ...   
296        69  2016           9.50          11.60       33988          1   
297        66  2015           4.00           5.90       60000          2   
298        69  2009           3.35          11.00       87934          2   
299        69  2017          11.50          12.50        9000          1   
300        66  2016           5.30           5.90        5464          2   

     Selling_type  Transmission  Owner  
0               0             1      0  
1               0             1      0  
2               0             1      0  
3               0             1      0  
4               0             1      0  
..            ...           ...    ...  
296             0             1      0  
297             0             1      0  
298             0             1      0  
299             0             1      0  
300             0             1      0  

[301 rows x 9 columns]

In [27]:
x = df.drop(["Selling_Price"],axis=1).values
y = df["Selling_Price"].values

In [28]:
x

array([[9.00e+01, 2.01e+03, 5.59e+00, ..., 0.00e+00, 1.00e+00, 0.00e+00],
       [9.30e+01, 2.01e+03, 9.54e+00, ..., 0.00e+00, 1.00e+00, 0.00e+00],
       [6.80e+01, 2.02e+03, 9.85e+00, ..., 0.00e+00, 1.00e+00, 0.00e+00],
       ...,
       [6.90e+01, 2.01e+03, 1.10e+01, ..., 0.00e+00, 1.00e+00, 0.00e+00],
       [6.90e+01, 2.02e+03, 1.25e+01, ..., 0.00e+00, 1.00e+00, 0.00e+00],
       [6.60e+01, 2.02e+03, 5.90e+00, ..., 0.00e+00, 1.00e+00, 0.00e+00]])

In [29]:
y

array([ 3.35,  4.75,  7.25,  2.85,  4.6 ,  9.25,  6.75,  6.5 ,  8.75,
        7.45,  2.85,  6.85,  7.5 ,  6.1 ,  2.25,  7.75,  7.25,  7.75,
        3.25,  2.65,  2.85,  4.9 ,  4.4 ,  2.5 ,  2.9 ,  3.  ,  4.15,
        6.  ,  1.95,  7.45,  3.1 ,  2.35,  4.95,  6.  ,  5.5 ,  2.95,
        4.65,  0.35,  3.  ,  2.25,  5.85,  2.55,  1.95,  5.5 ,  1.25,
        7.5 ,  2.65,  1.05,  5.8 ,  7.75, 14.9 , 23.  , 18.  , 16.  ,
        2.75,  3.6 ,  4.5 ,  4.75,  4.1 , 19.99,  6.95,  4.5 , 18.75,
       23.5 , 33.  ,  4.75, 19.75,  9.25,  4.35, 14.25,  3.95,  4.5 ,
        7.45,  2.65,  4.9 ,  3.95,  5.5 ,  1.5 ,  5.25, 14.5 , 14.73,
        4.75, 23.  , 12.5 ,  3.49,  2.5 , 35.  ,  5.9 ,  3.45,  4.75,
        3.8 , 11.25,  3.51, 23.  ,  4.  ,  5.85, 20.75, 17.  ,  7.05,
        9.65,  1.75,  1.7 ,  1.65,  1.45,  1.35,  1.35,  1.35,  1.25,
        1.2 ,  1.2 ,  1.2 ,  1.15,  1.15,  1.15,  1.15,  1.11,  1.1 ,
        1.1 ,  1.1 ,  1.05,  1.05,  1.05,  1.05,  1.  ,  0.95,  0.9 ,
        0.9 ,  0.75,

In [30]:
from sklearn.model_selection import train_test_split

In [31]:
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.2,random_state=0)

In [32]:
from sklearn.linear_model import LinearRegression

In [33]:
classifier = LinearRegression()

In [34]:
classifier.fit(xtrain,ytrain)

LinearRegression()

In [35]:
ypred = classifier.predict(xtest)

In [36]:
print(ypred)

[ 7.14e+00 -4.28e-01  4.29e+00  8.66e+00  1.42e+01  4.91e+00  3.53e+00
  1.45e+00  5.38e+00  4.66e+00  2.25e+00  1.63e+00  5.10e+00  7.64e+00
  8.25e+00  1.42e+01  7.39e+00  4.28e+00 -4.57e-01  2.38e+00  5.03e+00
  3.81e+00  6.49e+00  8.15e+00 -1.92e+00  1.93e+00 -8.13e-01  8.20e-01
  1.25e-02  7.21e+00  3.08e+00  7.06e+00  7.31e-01  7.55e+00  3.58e+00
  1.81e+00  5.60e+00  6.59e+00 -2.72e+00  8.76e+00  8.83e+00  1.99e+01
  4.40e+00  3.86e+00  6.27e+00  9.52e+00  1.24e-01  1.68e+00  5.18e+00
  6.96e+00  8.16e+00  4.20e+00  4.92e+00  2.03e+01  1.76e+00  1.31e+00
  2.97e-01  1.99e+00  3.41e+00  8.50e-01  3.59e+00]


In [37]:
np.set_printoptions(precision=2)

In [38]:
ypred

array([ 7.14e+00, -4.28e-01,  4.29e+00,  8.66e+00,  1.42e+01,  4.91e+00,
        3.53e+00,  1.45e+00,  5.38e+00,  4.66e+00,  2.25e+00,  1.63e+00,
        5.10e+00,  7.64e+00,  8.25e+00,  1.42e+01,  7.39e+00,  4.28e+00,
       -4.57e-01,  2.38e+00,  5.03e+00,  3.81e+00,  6.49e+00,  8.15e+00,
       -1.92e+00,  1.93e+00, -8.13e-01,  8.20e-01,  1.25e-02,  7.21e+00,
        3.08e+00,  7.06e+00,  7.31e-01,  7.55e+00,  3.58e+00,  1.81e+00,
        5.60e+00,  6.59e+00, -2.72e+00,  8.76e+00,  8.83e+00,  1.99e+01,
        4.40e+00,  3.86e+00,  6.27e+00,  9.52e+00,  1.24e-01,  1.68e+00,
        5.18e+00,  6.96e+00,  8.16e+00,  4.20e+00,  4.92e+00,  2.03e+01,
        1.76e+00,  1.31e+00,  2.97e-01,  1.99e+00,  3.41e+00,  8.50e-01,
        3.59e+00])

In [41]:
np.concatenate((ypred.reshape(len(ypred),1),ytest.reshape(len(ytest),1)),1)

array([[ 7.14e+00,  8.25e+00],
       [-4.28e-01,  5.00e-01],
       [ 4.29e+00,  5.25e+00],
       [ 8.66e+00,  9.50e+00],
       [ 1.42e+01,  1.80e+01],
       [ 4.91e+00,  5.50e+00],
       [ 3.53e+00,  3.75e+00],
       [ 1.45e+00,  4.50e-01],
       [ 5.38e+00,  4.50e+00],
       [ 4.66e+00,  4.50e+00],
       [ 2.25e+00,  2.70e+00],
       [ 1.63e+00,  7.20e-01],
       [ 5.10e+00,  5.25e+00],
       [ 7.64e+00,  7.50e+00],
       [ 8.25e+00,  7.75e+00],
       [ 1.42e+01,  1.98e+01],
       [ 7.39e+00,  7.40e+00],
       [ 4.28e+00,  4.75e+00],
       [-4.57e-01,  3.50e-01],
       [ 2.38e+00,  1.70e+00],
       [ 5.03e+00,  4.40e+00],
       [ 3.81e+00,  5.25e+00],
       [ 6.49e+00,  5.11e+00],
       [ 8.15e+00,  1.12e+01],
       [-1.92e+00,  2.00e-01],
       [ 1.93e+00,  7.80e-01],
       [-8.13e-01,  3.80e-01],
       [ 8.20e-01,  6.50e-01],
       [ 1.25e-02,  5.00e-01],
       [ 7.21e+00,  3.60e+00],
       [ 3.08e+00,  3.25e+00],
       [ 7.06e+00,  7.20e+00],
       [

In [43]:
from sklearn.metrics import mean_squared_error,mean_absolute_error,r2_score

In [44]:
mean_squared_error(ypred,ytest)

2.1882678322013245

In [45]:
mean_absolute_error(ypred,ytest)

0.9995912295505847

In [46]:
r2_score(ypred,ytest)

0.889031675906089

# It is 88% accurate